site_name: Delta Utils
theme:
    name: material
repo_url: https://github.com/bulv1ne/delta_utils
docs_dir: docs
nav:
    - Home: 'README.md'
    - 'User Guide':
      - 'usage.md'
      - 'clean.md'
    - 'About':
          - Issue Tracker: 'https://github.com/bulv1ne/delta_utils/issues'
          - 'CHANGELOG.md'
          - License: 'LICENSE.md'
plugins:
    - mkdocstrings:
        handlers:
          python:
            selection:
              docstring_style: google
        watch:
          - delta_utils/
    - search
    - RootFiles:
          files:
              - 'README.md'
              - 'CHANGELOG.md'
              - 'LICENSE.md'
